name: smokesentinel
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0  # <== pin for Colab compatibility
  - pytorch=2.1.0  # <== pin for Colab compatibility
  - torchvision=0.16.0  # <== pin for Colab compatibility
  - torchaudio=2.1.0  # <== pin for Colab compatibility
  - xarray=2023.12.0
  - rasterio=1.3.9
  - metpy=1.5.0
  - netCDF4=1.6.4
  - dask=2023.12.0
  - geopandas=0.14.1
  - pyarrow=14.0.1
  - optuna=3.4.0
  - shap=0.43.0
  - ipywidgets=8.1.1
  - plotly=5.18.0
  - scikit-learn=1.3.2
  - jupyter=1.0.0
  - pip=23.3.1
  # Phase 1 additions
  - aiohttp=3.9.1
  - httpx=0.26.0
  - pytest=7.4.4
  - pytest-asyncio=0.23.5
  - pydantic-settings=2.1.0
  - rich=13.7.0
  - pip:
    - requests==2.31.0
    - aiohttp==3.9.1
    - tqdm==4.66.1
    - torch-geometric==2.4.0
    - pytest-httpx==0.27.0 